meta:
  port: 10014
  host: 0.0.0.0
  run-mode: debug
  log-name: ./logs/console
  ppof: true
  swagger: true
  doc-host: 127.0.0.1:10014

server:
  bucket-period: 60 # token bucket fill period interval in seconds
  bucket-cap: 200   # token bucket capacity
  bucket-qua: 50    # token bucket quantum in every interval

github:
  def-limit: 20 # default limit query parameter value
  max-limit: 50 # maximum limit query parameter value
  token: xxx # token which is in repo scope and has read:user perm
