FORMAT: 1A
HOST: localhost:10014/

# common_api (1.0)

My common api collection

[Aoi-hosizora - Website](https://github.com/Aoi-hosizora)

[Send email to Aoi-hosizora](mailto:aoihosizora@hotmail.com)

# Group Github

github-controller

## Get rate limit status for the authenticated user [/github/rate_limit]

### Get rate limit status for the authenticated user [GET]

`GET /github/rate_limit`

See https://docs.github.com/en/rest/reference/rate-limit

+ Request (application/json)

    + Attributes

    + Headers

            Authorization: github token, format: Token xxx (string, required)

    + Body

+ Response 200 (application/json)

    + Attributes (string)

    + Headers

    + Body

## Get github user issues timeline (event) [/github/users/{name}/issues/timeline{?page}]

### Get github user issues timeline (event) [GET]

`GET /github/users/{name}/issues/timeline`

Fixed field: id?, node_id?, event(enum), actor(User), commit_id?, commit_url?, created_at(time), repo(string), number(integer), involve(string)

+ Parameters

    + name (string, required) - github username
    + page (number, optional) - query page
        (format: int32)

+ Request (application/json)

    + Attributes

    + Headers

            Authorization: github token, format: Token xxx (string, required)

    + Body

+ Response 200 (application/json)

    + Attributes (array[string])

    + Headers

    + Body

## Get raw page without authentication [/github/raw{?page}]

### Get raw page without authentication [GET]

`GET /github/raw`

+ Parameters

    + page (string, required) - Github url without github.com prefix

+ Request (application/json)

    + Attributes

    + Headers

    + Body

+ Response 200 (application/json)

    + Attributes (string)

    + Headers

    + Body

# Data Structures

## Result (object)

+ code (number, required) - status code
    (format: int32)
+ message (string, required) - status message
